#!/bin/sh
HERE="$(dirname "$(readlink -f "${0}")")"

# PATH
export PATH="${HERE}:${HERE}/usr/bin/:${HERE}/usr/sbin/:${HERE}/usr/games/:${HERE}/bin/:${HERE}/sbin/${PATH:+:$PATH}"

# LD_LIBRARY_PATH - dynamically add subdirectories of usr/lib and usr/lib64
if [ -d "${HERE}/usr/lib" ]; then
  for d in $(find "${HERE}/usr/lib" -type d 2>/dev/null); do
    export LD_LIBRARY_PATH="${d}:${LD_LIBRARY_PATH}"
  done
fi
if [ -d "${HERE}/usr/lib64" ]; then
  for d in $(find "${HERE}/usr/lib64" -type d 2>/dev/null); do
    export LD_LIBRARY_PATH="${d}:${LD_LIBRARY_PATH}"
  done
fi
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${HERE}/usr/lib/x86_64-linux-gnu/:${HERE}/usr/lib64/:${HERE}/lib/:${HERE}/lib64/:${HERE}/lib/x86_64-linux-gnu/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
#export LD_LIBRARY_PATH=/lib/:/lib64/:/lib/x86_64-linux-gnu/:/usr/lib/:"${LD_LIBRARY_PATH}" # Uncomment to use system libraries

# XDG_DATA_DIRS
DEFAULT_XDG_DATA_DIRS='./share/:/usr/share/gnome:/usr/local/share/:/usr/share/'
export XDG_DATA_DIRS="${HERE}/usr/share/:${XDG_DATA_DIRS:-$DEFAULT_XDG_DATA_DIRS}"

# Python - dynamically detect version
if test -d "${HERE}"/usr/lib/python*; then
  PYTHONVERSION=$(find "${HERE}"/usr/lib -maxdepth 1 -type d -name "python*" | head -1 | sed 's:.*/::')
  export PYTHONPATH="${HERE}/usr/share/pyshared/:${HERE}/usr/lib/${PYTHONVERSION}/site-packages/:${HERE}/usr/lib/${PYTHONVERSION}/lib-dynload/${PYTHONPATH:+:$PYTHONPATH}"
  export PYTHONHOME="${HERE}/usr/"
fi

# Perl
export PERLLIB="${HERE}/usr/share/perl5/:${HERE}/usr/lib/perl5/${PERLLIB:+:$PERLLIB}"

# GObject Introspection
export GI_TYPELIB_PATH="${HERE}/usr/lib/girepository-1.0/:${HERE}/usr/lib64/girepository-1.0/${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}"

# GSettings
export GSETTINGS_SCHEMA_DIR="${HERE}/usr/share/glib-2.0/schemas/${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}"

# GStreamer
export GST_PLUGIN_SCANNER="${HERE}/usr/libexec/gstreamer-1.0/gst-plugin-scanner"

# Qt - dynamically detect version and set plugin path
QTVER=$(find "${HERE}"/usr/lib "${HERE}"/usr/lib64 -maxdepth 1 -type d -name "qt*" 2>/dev/null | head -1 | sed 's:.*/::')
if [ -n "$QTVER" ]; then
  export QT_PLUGIN_PATH="${HERE}/usr/lib/${QTVER}/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/${QTVER}/plugins/:${HERE}/usr/lib64/${QTVER}/plugins/:${HERE}/lib/${QTVER}/plugins/:${HERE}/lib64/${QTVER}/plugins/${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}"
  export QML2_IMPORT_PATH="${HERE}/usr/lib64/qml/:${HERE}/usr/lib/qml/:${HERE}/usr/lib/${QTVER}/qml/:${HERE}/usr/lib64/${QTVER}/qml/${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}"
else
  export QT_PLUGIN_PATH="${HERE}/usr/lib64/plugins/:${HERE}/usr/lib/plugins/:${HERE}/usr/lib/qt4/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt4/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt4/plugins/:${HERE}/usr/lib32/qt4/plugins/:${HERE}/usr/lib64/qt4/plugins/:${HERE}/usr/lib/qt5/plugins/:${HERE}/usr/lib/i386-linux-gnu/qt5/plugins/:${HERE}/usr/lib/x86_64-linux-gnu/qt5/plugins/:${HERE}/usr/lib32/qt5/plugins/:${HERE}/usr/lib/qt6/plugins/:${HERE}/usr/lib64/qt6/plugins/:${HERE}/usr/lib64/qt5/plugins/${QT_PLUGIN_PATH:+:$QT_PLUGIN_PATH}"
  export QML2_IMPORT_PATH="${HERE}/usr/lib64/qml/:${HERE}/usr/lib/qml/:${HERE}/usr/lib/qt5/qml/:${HERE}/usr/lib64/qt5/qml/${QML2_IMPORT_PATH:+:$QML2_IMPORT_PATH}"
fi

# GNOME Folks
export FOLKS_BACKEND_PATH="${HERE}/usr/lib64/folks/26/backends/${FOLKS_BACKEND_PATH:+:$FOLKS_BACKEND_PATH}"

# Mozilla
export MOZ_LEGACY_PROFILES=1 # Prevent per installation profiles

# Execute the application
EXEC=$(grep -e '^Exec=.*' "${HERE}"/*.desktop | head -n 1 | cut -d "=" -f 2- | sed -e 's|%.||g')
exec ${EXEC} "$@"
